### ISSUE TITLE
新增账号的问题

### ISSUE THREAD

**Issue by vakinge** [bumoproject/bumo#2]
我本地运行了bumo链测试网络，但是在运行demo的时候遇到了几个疑问。

1. 调用/createAccount创建的账号，用/getAccount查询提示不存在
2.调用/createAccount创建的账号与发起交易CREATE_ACCOUNT有什么区别？
3.是不是需要发起交易CREATE_ACCOUNT才会真正创建成功？如果是我怎么初始化一个已经存在发起交易的address

**Comment by zjg555543** [comment]
1、使用 `createAccount` 接口创建的账号仅生成一个公私钥对，但不会对区块链的数据产生影响，即不会上链。而 `getAccount` 查询的是区块链上的数据，所以是查不到这个账号的。
2、发起交易 `CREATE_ACCOUNT` ，是在把账号写入链中，即全网可查询到这个账号。

**Comment by vakinge** [comment]
发起交易 CREATE_ACCOUNT ，按我理解这就存在一个鸡和蛋的问题。因为发起交易需要由一个账号去发起，但是我现在还没有账号。不知道是不是我理解的问题

**Comment by vakinge** [comment]
我尝试过使用创世账号，但是没有找到公钥和私钥。发起交易不是还需要对应的公私钥么

**Comment by zjg555543** [comment]
以 linux 为示例，假设 `bumo` 为可执行程序，设置创世账号的过程如下：

生成一个账号公私钥对：
```
[root@bumo buchain]# ./bin/bumo --create-account
{
   "address" : "buQpabu2F9dcKd1hpfXXT4Ei8kTCBna6qoPc",
   "private_key" : "privbtBCWEr1PFbuhS3s3q33c34TWKYMtRuWVMR3cGvtURM3BvzesxR3",
   "private_key_aes" : "9453afbbfbb5bf4606c3e83f0a4bc8168af95660907aa4ad175fc10109101b2380e6d75503f61cb23beddee8ea78870d0ed8f35db905ff17affc823d20054745",
   "public_key" : "b00120eea9365eb8db06ebe07c3c31ac44b95f0a15249e5bbed0858839aa1515365b2be812dc",
   "public_key_raw" : "20eea9365eb8db06ebe07c3c31ac44b95f0a15249e5bbed0858839aa1515365b",
   "sign_type" : "ed25519"
}
```

修改创世账号的配置：
```
[root@bumo buchain]#  vim config/bumo.json

genesis.account  ->  buQpabu2F9dcKd1hpfXXT4Ei8kTCBna6qoPc
```

清空数据

```
[root@bumo buchain]# ./bin/bumo --dropdb
```

再次启动

```
[root@bumo buchain]# ./bin/bumo
```

此时就可以用创世账号交易了。创世账号即 `buQpabu2F9dcKd1hpfXXT4Ei8kTCBna6qoPc`

**Comment by vakinge** [comment]
我已经按你说的步骤操作了 ，然后我通过查询创世账号接口读取的还是之前默认的那个 。是不是还需要修改validators和p2p.known_peers两个地方的配置，如果需要应该怎么配置

**Comment by vakinge** [comment]
问题已解决。
清空数据前需要先停止bumo服务
