### ISSUE TITLE
 contractBasedToken.js中的代码报错

### ISSUE THREAD

**Issue by JenniferZang** [bumoproject/bumo#21]
用contractBasedToken.js中的代码创建智能合约，
使用JS的SDK sdk.contract.getAddress无法查到创建好的合约地址，
使用getTransactionHistory?hash命令查询时 报错"error_code":151,"error_desc":"{\"contract\",\"exception\":\"SyntaxError: Unexpected end of JSON input\ 
后来自己编写智能合约代码，虽然在jslint中通过后压缩，也会出现这个问题
定位了下代码主要是如果有变量定义在函数外或者有JSON.parse就会报错151，但是都能在jslint中通过。

**Comment by JenniferZang** [comment]
,\"exception\":\"SyntaxError: Unexpected end of JSON input\",\"linenum\":1,\"stack\":\"SyntaxError: Unexpected end of JSON input\\n    at JSON.parse (<anonymous>)\\n    at init (__enable_check_time__:1:3044)\"}" 补充一点报错信息

**Comment by frm430342210** [comment]
> 用contractBasedToken.js中的代码创建智能合约，
> 使用JS的SDK sdk.contract.getAddress无法查到创建好的合约地址，
> 使用getTransactionHistory?hash命令查询时 报错"error_code":151,"error_desc":"{"contract","exception":"SyntaxError: Unexpected end of JSON input\
> 后来自己编写智能合约代码，虽然在jslint中通过后压缩，也会出现这个问题
> 定位了下代码主要是如果有变量定义在函数外或者有JSON.parse就会报错151，但是都能在jslint中通过。

您好，
1. jslint检测通过，说明合约语法没有问题。
2. 但是您报的这个错，是因为用JSON.parse来解析参数，如果参数不是JSON格式或者参数是undefine时，都会报这个错误。
3. 在创建合约时，有一个initInput，这个就是在创建合约时，传递给Init函数的参数。也就是说，这个参数需要是JSON格式的字符串。

**Comment by JenniferZang** [comment]
了解了 在更改initInput后解决了问题 非常感谢

**Comment by JenniferZang** [comment]
> 
> 
> > 用contractBasedToken.js中的代码创建智能合约，
> > 使用JS的SDK sdk.contract.getAddress无法查到创建好的合约地址，
> > 使用getTransactionHistory?hash命令查询时 报错"error_code":151,"error_desc":"{"contract","exception":"SyntaxError: Unexpected end of JSON input
> > 后来自己编写智能合约代码，虽然在jslint中通过后压缩，也会出现这个问题
> > 定位了下代码主要是如果有变量定义在函数外或者有JSON.parse就会报错151，但是都能在jslint中通过。
> 
> 您好，
> 
>     1. jslint检测通过，说明合约语法没有问题。
> 
>     2. 但是您报的这个错，是因为用JSON.parse来解析参数，如果参数不是JSON格式或者参数是undefine时，都会报这个错误。
> 
>     3. 在创建合约时，有一个initInput，这个就是在创建合约时，传递给Init函数的参数。也就是说，这个参数需要是JSON格式的字符串。

了解了 在更改initInput后解决了问题 非常感谢
