### ISSUE TITLE
怎么布置合约？

### ISSUE THREAD

**Issue by qq6690876** [bumoproject/bumo#6]
已经将合约写好了，怎么布置上链呢？

**Comment by kk47** [comment]
@qq6690876 参考BUMO 区块链开发文档: HTTP接口->创建账号-> 创建合约账号

**Comment by qq6690876** [comment]
请问需要用protocol buffer3对代码做序列化，然后填入callContract 中的code字段？

**Comment by kk47** [comment]
@qq6690876  创建智能合约使用的是submitTransaction接口。 callContract是用来测试智能合约的。如果只需要测试合约代码，不创建合约账号，可以将合约代码写入code字段，不需要序列号

**Comment by qq6690876** [comment]
@kk47 谢谢，很透彻。
