### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by prettyCoders** [bumoproject/bumo#9]
Is Ubuntu 16.04 not supported？

**Comment by bumo-source** [comment]
BUMO supports compiling its source code on ubuntu 16， but it does not supports installation with the "make install" command.

**Comment by prettyCoders** [comment]
@bumo-source Can I run nodes on Ubuntu 16.04

**Comment by bumo-source** [comment]
Yes

**Comment by prettyCoders** [comment]
Thanks

**Comment by zjg555543** [comment]
BUMO is currently available for Ubuntu, Centos and most of the operating systems, it is recommended that you have Ubuntu 14.04 or Centos 7.

BUMO supports compiling its source code on ubuntu 16, but it does not supports installation with the "make install" command.

This is the link.
[Installation on Linux](https://github.com/bumoproject/bumo/blob/master/docs/manual.md#linux)
